In [30]:
pip install pymongo

Requirement already satisfied: pymongo in c:\users\akumaravel\.conda\envs\dataengineeringcog\lib\site-packages (4.0.2)
Note: you may need to restart the kernel to use updated packages.

In [31]:
import pymongo
import pprint
from pprint import pprint

In [41]:
import pandas as pd
import json

In [32]:

# declare database and collection instances
EltData = client["EltData"]
col = EltData.geonames

In [33]:
col=EltData["geonames"]
for x in col.find():
    pprint(x)

{'': '',
 '_id': ObjectId('6229044036c49561fbe12f56'),
 'admin1': 'United States',
 'admin2': 'West Virginia',
 'admin3': 'Marion',
 'code': 'Four States',
 'country': '26572',
 'place': '1'}
{'_id': ObjectId('6229044036c49561fbe12f57'),
 'code': '\xa0\xa0\xa039.48/-80.31',
 'place': ''}
{'': '',
 '_id': ObjectId('6229044036c49561fbe12f58'),
 'admin1': 'United States',
 'admin2': 'Maryland',
 'admin3': 'Frederick',
 'code': 'Myersville',
 'country': '21773',
 'place': '2'}
{'_id': ObjectId('6229044036c49561fbe12f59'),
 'code': '\xa0\xa0\xa039.528/-77.551',
 'place': ''}
{'': '',
 '_id': ObjectId('6229044036c49561fbe12f5a'),
 'admin1': 'United States',
 'admin2': 'Virginia',
 'admin3': 'Fairfax',
 'code': 'Fairfax',
 'country': '22033',
 'place': '3'}
{'_id': ObjectId('6229044036c49561fbe12f5b'),
 'code': '\xa0\xa0\xa038.878/-77.388',
 'place': ''}
{'': '',
 '_id': ObjectId('6229044036c49561fbe12f5c'),
 'admin1': 'United States',
 'admin2': 'Virginia',
 'admin3': 'Fairfax',
 'code': 'Alexandria',
 'country': '22303',
 'place': '4'}
{'_id': ObjectId('6229044036c49561fbe12f5d'),
 'code': '\xa0\xa0\xa038.791/-77.081',
 'place': ''}
{'': '',
 '_id': ObjectId('6229044036c49561fbe12f5e'),
 'admin1': 'United States',
 'admin2': 'Virginia',
 'admin3': 'Fairfax',
 'code': 'Alexandria',
 'country': '22306',
 'place': '5'}
{'_id': ObjectId('6229044036c49561fbe12f5f'),
 'code': '\xa0\xa0\xa038.759/-77.087',
 'place': ''}
{'': '',
 '_id': ObjectId('6229044036c49561fbe12f60'),
 'admin1': 'United States',
 'admin2': 'Virginia',
 'admin3': 'Fairfax',
 'code': 'Alexandria',
 'country': '22310',
 'place': '6'}
{'_id': ObjectId('6229044036c49561fbe12f61'),
 'code': '\xa0\xa0\xa038.779/-77.119',
 'place': ''}
{'': '',
 '_id': ObjectId('6229044036c49561fbe12f62'),
 'admin1': 'United States',
 'admin2': 'Virginia',
 'admin3': 'Fairfax',
 'code': 'Alexandria',
 'country': '22312',
 'place': '7'}
{'_id': ObjectId('6229044036c49561fbe12f63'),
 'code': '\xa0\xa0\xa038.819/-77.148',
 'place': ''}
{'': '',
 '_id': ObjectId('6229044036c49561fbe12f64'),
 'admin1': 'United States',
 'admin2': 'Virginia',
 'admin3': 'James City',
 'code': 'Williamsburg',
 'country': '23185',
 'place': '8'}
{'_id': ObjectId('6229044036c49561fbe12f65'),
 'code': '\xa0\xa0\xa037.273/-76.732',
 'place': ''}
{'': '',
 '_id': ObjectId('6229044036c49561fbe12f66'),
 'admin1': 'United States',
 'admin2': 'Virginia',
 'admin3': 'Henrico',
 'code': 'Richmond',
 'country': '23230',
 'place': '9'}
{'_id': ObjectId('6229044036c49561fbe12f67'),
 'code': '\xa0\xa0\xa037.592/-77.495',
 'place': ''}
{'': '',
 '_id': ObjectId('6229044036c49561fbe12f68'),
 'admin1': 'United States',
 'admin2': 'Virginia',
 'admin3': 'Henrico',
 'code': 'Henrico',
 'country': '23233',
 'place': '10'}
{'_id': ObjectId('6229044036c49561fbe12f69'),
 'code': '\xa0\xa0\xa037.464/-77.398',
 'place': ''}
{'': '',
 '_id': ObjectId('6229044036c49561fbe12f6a'),
 'admin1': 'United States',
 'admin2': 'Georgia',
 'admin3': 'DeKalb',
 'code': 'Scottdale',
 'country': '30079',
 'place': '11'}
{'_id': ObjectId('6229044036c49561fbe12f6b'),
 'code': '\xa0\xa0\xa033.793/-84.259',
 'place': ''}
{'': '',
 '_id': ObjectId('6229044036c49561fbe12f6c'),
 'admin1': 'United States',
 'admin2': 'Georgia',
 'admin3': 'Clayton',
 'code': 'Conley',
 'country': '30288',
 'place': '12'}
{'_id': ObjectId('6229044036c49561fbe12f6d'),
 'code': '\xa0\xa0\xa033.637/-84.337',
 'place': ''}
{'': '',
 '_id': ObjectId('6229044036c49561fbe12f6e'),
 'admin1': 'United States',
 'admin2': 'Georgia',
 'admin3': 'Clayton',
 'code': 'Ellenwood',
 'country': '30294',
 'place': '13'}
{'_id': ObjectId('6229044036c49561fbe12f6f'),
 'code': '\xa0\xa0\xa033.617/-84.294',
 'place': ''}
{'': '',
 '_id': ObjectId('6229044036c49561fbe12f70'),
 'admin1': 'United States',
 'admin2': 'Georgia',
 'admin3': 'DeKalb',
 'code': 'Atlanta',
 'country': '30319',
 'place': '14'}
{'_id': ObjectId('6229044036c49561fbe12f71'),
 'code': '\xa0\xa0\xa033.869/-84.335',
 'place': ''}
{'': '',
 '_id': ObjectId('6229044036c49561fbe12f72'),
 'admin1': 'United States',
 'admin2': 'Georgia',
 'admin3': 'DeKalb',
 'code': 'Atlanta',
 'country': '30329',
 'place': '15'}
{'_id': ObjectId('6229044036c49561fbe12f73'),
 'code': '\xa0\xa0\xa033.824/-84.321',
 'place': ''}
{'': '',
 '_id': ObjectId('6229044036c49561fbe12f74'),
 'admin1': 'United States',
 'admin2': 'Georgia',
 'admin3': 'DeKalb',
 'code': 'Atlanta',
 'country': '30341',
 'place': '16'}
{'_id': ObjectId('6229044036c49561fbe12f75'),
 'code': '\xa0\xa0\xa033.888/-84.29',
 'place': ''}
{'': '',
 '_id': ObjectId('6229044036c49561fbe12f76'),
 'admin1': 'United States',
 'admin2': 'Georgia',
 'admin3': 'DeKalb',
 'code': 'Atlanta',
 'country': '30345',
 'place': '17'}
{'_id': ObjectId('6229044036c49561fbe12f77'),
 'code': '\xa0\xa0\xa033.851/-84.287',
 'place': ''}
{'': '',
 '_id': ObjectId('6229044036c49561fbe12f78'),
 'admin1': 'United States',
 'admin2': 'Georgia',
 'admin3': 'DeKalb',
 'code': 'Atlanta',
 'country': '30346',
 'place': '18'}
{'_id': ObjectId('6229044036c49561fbe12f79'),
 'code': '\xa0\xa0\xa033.927/-84.333',
 'place': ''}
{'': '',
 '_id': ObjectId('6229044036c49561fbe12f7a'),
 'admin1': 'United States',
 'admin2': 'Florida',
 'admin3': 'Nassau',
 'code': 'Yulee',
 'country': '32041',
 'place': '19'}
{'_id': ObjectId('6229044036c49561fbe12f7b'),
 'code': '\xa0\xa0\xa030.623/-81.59',
 'place': ''}
{'': '',
 '_id': ObjectId('6229044036c49561fbe12f7c'),
 'admin1': 'United States',
 'admin2': 'Florida',
 'admin3': 'Volusia',
 'code': 'Edgewater',
 'country': '32132',
 'place': '20'}
{'_id': ObjectId('6229044036c49561fbe12f7d'),
 'code': '\xa0\xa0\xa028.982/-80.91',
 'place': ''}
{'': '',
 '_id': ObjectId('6229044036c49561fbe12f7e'),
 'admin1': 'United States',
 'admin2': 'Florida',
 'admin3': 'Jackson',
 'code': 'Cypress',
 'country': '32432',
 'place': '21'}
{'_id': ObjectId('6229044036c49561fbe12f7f'),
 'code': '\xa0\xa0\xa030.716/-85.078',
 'place': ''}
{'': '',
 '_id': ObjectId('6229044036c49561fbe12f80'),
 'admin1': 'United States',
 'admin2': 'Florida',
 'admin3': 'Alachua',
 'code': 'Alachua',
 'country': '32615',
 'place': '22'}
{'_id': ObjectId('6229044036c49561fbe12f81'),
 'code': '\xa0\xa0\xa029.813/-82.472',
 'place': ''}
{'': '',
 '_id': ObjectId('6229044036c49561fbe12f82'),
 'admin1': 'United States',
 'admin2': 'Florida',
 'admin3': 'Levy',
 'code': 'Chiefland',
 'country': '32626',
 'place': '23'}
{'_id': ObjectId('6229044036c49561fbe12f83'),
 'code': '\xa0\xa0\xa029.483/-82.881',
 'place': ''}
{'': '',
 '_id': ObjectId('6229044036c49561fbe12f84'),
 'admin1': 'United States',
 'admin2': 'Florida',
 'admin3': 'Putnam',
 'code': 'Melrose',
 'country': '32666',
 'place': '24'}
{'_id': ObjectId('6229044036c49561fbe12f85'),
 'code': '\xa0\xa0\xa029.732/-82.028',
 'place': ''}
{'': '',
 '_id': ObjectId('6229044036c49561fbe12f86'),
 'admin1': 'United States',
 'admin2': 'Florida',
 'admin3': 'Brevard',
 'code': 'Mims',
 'country': '32754',
 'place': '25'}
{'_id': ObjectId('6229044036c49561fbe12f87'),
 'code': '\xa0\xa0\xa028.697/-80.866',
 'place': ''}
{'': '',
 '_id': ObjectId('6229044036c49561fbe12f88'),
 'admin1': 'United States',
 'admin2': 'Florida',
 'admin3': 'Seminole',
 'code': 'Sanford',
 'country': '32771',
 'place': '26'}
{'_id': ObjectId('6229044036c49561fbe12f89'),
 'code': '\xa0\xa0\xa028.801/-81.285',
 'place': ''}
{'': '',
 '_id': ObjectId('6229044036c49561fbe12f8a'),
 'admin1': 'United States',
 'admin2': 'Florida',
 'admin3': 'Hillsborough',
 'code': 'Lutz',
 'country': '33548',
 'place': '27'}
{'_id': ObjectId('6229044036c49561fbe12f8b'),
 'code': '\xa0\xa0\xa028.139/-82.482',
 'place': ''}
{'': '',
 '_id': ObjectId('6229044036c49561fbe12f8c'),
 'admin1': 'United States',
 'admin2': 'Florida',
 'admin3': 'Hillsborough',
 'code': 'Lutz',
 'country': '33549',
 'place': '28'}
{'_id': ObjectId('6229044036c49561fbe12f8d'),
 'code': '\xa0\xa0\xa028.137/-82.461',
 'place': ''}
{'': '',
 '_id': ObjectId('6229044036c49561fbe12f8e'),
 'admin1': 'United States',
 'admin2': 'Florida',
 'admin3': 'Hillsborough',
 'code': 'Odessa',
 'country': '33556',
 'place': '29'}
{'_id': ObjectId('6229044036c49561fbe12f8f'),
 'code': '\xa0\xa0\xa028.142/-82.591',
 'place': ''}
{'': '',
 '_id': ObjectId('6229044036c49561fbe12f90'),
 'admin1': 'United States',
 'admin2': 'Florida',
 'admin3': 'Hillsborough',
 'code': 'Seffner',
 'country': '33583',
 'place': '30'}
{'_id': ObjectId('6229044036c49561fbe12f91'),
 'code': '\xa0\xa0\xa027.872/-82.439',
 'place': ''}
{'': '',
 '_id': ObjectId('6229044036c49561fbe12f92'),
 'admin1': 'United States',
 'admin2': 'Florida',
 'admin3': 'Hillsborough',
 'code': 'Valrico',
 'country': '33594',
 'place': '31'}
{'_id': ObjectId('6229044036c49561fbe12f93'),
 'code': '\xa0\xa0\xa027.941/-82.242',
 'place': ''}
{'': '',
 '_id': ObjectId('6229044036c49561fbe12f94'),
 'admin1': 'United States',
 'admin2': 'Florida',
 'admin3': 'Hillsborough',
 'code': 'Wimauma',
 'country': '33598',
 'place': '32'}
{'_id': ObjectId('6229044036c49561fbe12f95'),
 'code': '\xa0\xa0\xa027.701/-82.315',
 'place': ''}
{'': '',
 '_id': ObjectId('6229044036c49561fbe12f96'),
 'admin1': 'United States',
 'admin2': 'Florida',
 'admin3': 'Lee',
 'code': 'Captiva',
 'country': '33924',
 'place': '33'}
{'_id': ObjectId('6229044036c49561fbe12f97'),
 'code': '\xa0\xa0\xa026.521/-82.18',
 'place': ''}
{'': '',
 '_id': ObjectId('6229044036c49561fbe12f98'),
 'admin1': 'United States',
 'admin2': 'Florida',
 'admin3': 'Charlotte',
 'code': 'Placida',
 'country': '33946',
 'place': '34'}
{'_id': ObjectId('6229044036c49561fbe12f99'),
 'code': '\xa0\xa0\xa026.832/-82.265',
 'place': ''}
{'': '',
 '_id': ObjectId('6229044036c49561fbe12f9a'),
 'admin1': 'United States',
 'admin2': 'Florida',
 'admin3': 'Sarasota',
 'code': 'Laurel',
 'country': '34272',
 'place': '35'}
{'_id': ObjectId('6229044036c49561fbe12f9b'),
 'code': '\xa0\xa0\xa027.147/-82.426',
 'place': ''}
{'': '',
 '_id': ObjectId('6229044036c49561fbe12f9c'),
 'admin1': 'United States',
 'admin2': 'Florida',
 'admin3': 'Sarasota',
 'code': 'Nokomis',
 'country': '34274',
 'place': '36'}
{'_id': ObjectId('6229044036c49561fbe12f9d'),
 'code': '\xa0\xa0\xa027.144/-82.464',
 'place': ''}
{'': '',
 '_id': ObjectId('6229044036c49561fbe12f9e'),
 'admin1': 'United States',
 'admin2': 'Florida',
 'admin3': 'Marion',
 'code': 'Dunnellon',
 'country': '34430',
 'place': '37'}
{'_id': ObjectId('6229044036c49561fbe12f9f'),
 'code': '\xa0\xa0\xa029.049/-82.461',
 'place': ''}
{'': '',
 '_id': ObjectId('6229044036c49561fbe12fa0'),
 'admin1': 'United States',
 'admin2': 'Florida',
 'admin3': 'Marion',
 'code': 'Dunnellon',
 'country': '34431',
 'place': '38'}
{'_id': ObjectId('6229044036c49561fbe12fa1'),
 'code': '\xa0\xa0\xa029.139/-82.533',
 'place': ''}
{'': '',
 '_id': ObjectId('6229044036c49561fbe12fa2'),
 'admin1': 'United States',
 'admin2': 'Florida',
 'admin3': 'Marion',
 'code': 'Dunnellon',
 'country': '34432',
 'place': '39'}
{'_id': ObjectId('6229044036c49561fbe12fa3'),
 'code': '\xa0\xa0\xa029.102/-82.341',
 'place': ''}
{'': '',
 '_id': ObjectId('6229044036c49561fbe12fa4'),
 'admin1': 'United States',
 'admin2': 'Florida',
 'admin3': 'Citrus',
 'code': 'Dunnellon',
 'country': '34433',
 'place': '40'}
{'_id': ObjectId('6229044036c49561fbe12fa5'),
 'code': '\xa0\xa0\xa028.995/-82.52',
 'place': ''}
{'': '',
 '_id': ObjectId('6229044036c49561fbe12fa6'),
 'admin1': 'United States',
 'admin2': 'Florida',
 'admin3': 'Citrus',
 'code': 'Hernando',
 'country': '34442',
 'place': '41'}
{'_id': ObjectId('6229044036c49561fbe12fa7'),
 'code': '\xa0\xa0\xa028.922/-82.39',
 'place': ''}
{'': '',
 '_id': ObjectId('6229044036c49561fbe12fa8'),
 'admin1': 'United States',
 'admin2': 'Florida',
 'admin3': 'Citrus',
 'code': 'Homosassa',
 'country': '34446',
 'place': '42'}
{'_id': ObjectId('6229044036c49561fbe12fa9'),
 'code': '\xa0\xa0\xa028.751/-82.514',
 'place': ''}
{'': '',
 '_id': ObjectId('6229044036c49561fbe12faa'),
 'admin1': 'United States',
 'admin2': 'Florida',
 'admin3': 'Citrus',
 'code': 'Homosassa',
 'country': '34448',
 'place': '43'}
{'_id': ObjectId('6229044036c49561fbe12fab'),
 'code': '\xa0\xa0\xa028.788/-82.568',
 'place': ''}
{'': '',
 '_id': ObjectId('6229044036c49561fbe12fac'),
 'admin1': 'United States',
 'admin2': 'Florida',
 'admin3': 'Citrus',
 'code': 'Lecanto',
 'country': '34460',
 'place': '44'}
{'_id': ObjectId('6229044036c49561fbe12fad'),
 'code': '\xa0\xa0\xa028.859/-82.509',
 'place': ''}
{'': '',
 '_id': ObjectId('6229044036c49561fbe12fae'),
 'admin1': 'United States',
 'admin2': 'Florida',
 'admin3': 'Citrus',
 'code': 'Homosassa',
 'country': '34487',
 'place': '45'}
{'_id': ObjectId('6229044036c49561fbe12faf'),
 'code': '\xa0\xa0\xa028.781/-82.615',
 'place': ''}
{'': '',
 '_id': ObjectId('6229044036c49561fbe12fb0'),
 'admin1': 'United States',
 'admin2': 'Florida',
 'admin3': 'Marion',
 'code': 'Summerfield',
 'country': '34491',
 'place': '46'}
{'_id': ObjectId('6229044036c49561fbe12fb1'),
 'code': '\xa0\xa0\xa029.011/-82.032',
 'place': ''}
{'': '',
 '_id': ObjectId('6229044036c49561fbe12fb2'),
 'admin1': 'United States',
 'admin2': 'Florida',
 'admin3': 'Pasco',
 'code': 'Hudson',
 'country': '34667',
 'place': '47'}
{'_id': ObjectId('6229044036c49561fbe12fb3'),
 'code': '\xa0\xa0\xa028.365/-82.676',
 'place': ''}
{'': '',
 '_id': ObjectId('6229044036c49561fbe12fb4'),
 'admin1': 'United States',
 'admin2': 'Florida',
 'admin3': 'Pasco',
 'code': 'Holiday',
 'country': '34690',
 'place': '48'}
{'_id': ObjectId('6229044036c49561fbe12fb5'),
 'code': '\xa0\xa0\xa028.191/-82.728',
 'place': ''}
{'': '',
 '_id': ObjectId('6229044036c49561fbe12fb6'),
 'admin1': 'United States',
 'admin2': 'Ohio',
 'admin3': 'Licking',
 'code': 'Hebron',
 'country': '43025',
 'place': '49'}
{'_id': ObjectId('6229044036c49561fbe12fb7'),
 'code': '\xa0\xa0\xa039.953/-82.492',
 'place': ''}
{'': '',
 '_id': ObjectId('6229044036c49561fbe12fb8'),
 'admin1': 'United States',
 'admin2': 'Indiana',
 'admin3': 'Boone',
 'code': 'Lebanon',
 'country': '46052',
 'place': '50'}
{'_id': ObjectId('6229044036c49561fbe12fb9'),
 'code': '\xa0\xa0\xa040.045/-86.464',
 'place': ''}
{'': '',
 '_id': ObjectId('6229044036c49561fbe12fba'),
 'admin1': 'United States',
 'admin2': 'Michigan',
 'admin3': 'Wayne',
 'code': 'Belleville',
 'country': '48111',
 'place': '51'}
{'_id': ObjectId('6229044036c49561fbe12fbb'),
 'code': '\xa0\xa0\xa042.195/-83.485',
 'place': ''}
{'': '',
 '_id': ObjectId('6229044036c49561fbe12fbc'),
 'admin1': 'United States',
 'admin2': 'Wisconsin',
 'admin3': 'Washington',
 'code': 'Germantown',
 'country': '53022',
 'place': '52'}
{'_id': ObjectId('6229044036c49561fbe12fbd'),
 'code': '\xa0\xa0\xa043.219/-88.117',
 'place': ''}
{'': '',
 '_id': ObjectId('6229044036c49561fbe12fbe'),
 'admin1': 'United States',
 'admin2': 'Illinois',
 'admin3': 'DuPage',
 'code': 'Itasca',
 'country': '60143',
 'place': '53'}
{'_id': ObjectId('6229044036c49561fbe12fbf'),
 'code': '\xa0\xa0\xa041.972/-88.02',
 'place': ''}
{'': '',
 '_id': ObjectId('6229044036c49561fbe12fc0'),
 'admin1': 'United States',
 'admin2': 'Illinois',
 'admin3': 'DuPage',
 'code': 'Hinsdale',
 'country': '60521',
 'place': '54'}
{'_id': ObjectId('6229044036c49561fbe12fc1'),
 'code': '\xa0\xa0\xa041.8/-87.929',
 'place': ''}
{'': '',
 '_id': ObjectId('6229044036c49561fbe12fc2'),
 'admin1': 'United States',
 'admin2': 'Illinois',
 'admin3': 'DuPage',
 'code': 'Willowbrook',
 'country': '60527',
 'place': '55'}
{'_id': ObjectId('6229044036c49561fbe12fc3'),
 'code': '\xa0\xa0\xa041.745/-87.933',
 'place': ''}
{'': '',
 '_id': ObjectId('6229044036c49561fbe12fc4'),
 'admin1': 'United States',
 'admin2': 'Texas',
 'admin3': 'Lamar',
 'code': 'Paris',
 'country': '75462',
 'place': '56'}
{'_id': ObjectId('6229044036c49561fbe12fc5'),
 'code': '\xa0\xa0\xa033.68/-95.491',
 'place': ''}
{'': '',
 '_id': ObjectId('6229044036c49561fbe12fc6'),
 'admin1': 'United States',
 'admin2': 'Nevada',
 'admin3': 'Douglas',
 'code': 'Gardnerville',
 'country': '89410',
 'place': '57'}
{'_id': ObjectId('6229044036c49561fbe12fc7'),
 'code': '\xa0\xa0\xa038.87/-119.611',
 'place': ''}
{'': '',
 '_id': ObjectId('6229044036c49561fbe12fc8'),
 'admin1': 'United States',
 'admin2': 'California',
 'admin3': 'Los Angeles',
 'code': 'Chatsworth',
 'country': '91311',
 'place': '58'}
{'_id': ObjectId('6229044036c49561fbe12fc9'),
 'code': '\xa0\xa0\xa034.258/-118.591',
 'place': ''}
{'': '',
 '_id': ObjectId('6229044036c49561fbe12fca'),
 'admin1': 'United States',
 'admin2': 'Hawaii',
 'admin3': 'Maui',
 'code': 'Kihei',
 'country': '96753',
 'place': '59'}
{'_id': ObjectId('6229044036c49561fbe12fcb'),
 'code': '\xa0\xa0\xa020.744/-156.448',
 'place': ''}
{'': '',
 '_id': ObjectId('6229044036c49561fbe12fcc'),
 'admin1': 'United States',
 'admin2': 'Alabama',
 'admin3': 'Mobile',
 'code': 'Mount Vernon',
 'country': '36560',
 'place': '60'}
{'_id': ObjectId('6229044036c49561fbe12fcd'),
 'code': '\xa0\xa0\xa031.097/-88.035',
 'place': ''}
{'': '',
 '_id': ObjectId('6229044036c49561fbe12fce'),
 'admin1': 'United States',
 'admin2': 'New York',
 'admin3': 'Suffolk',
 'code': 'Holtsville',
 'country': '00501',
 'place': '61'}
{'_id': ObjectId('6229044036c49561fbe12fcf'),
 'code': '\xa0\xa0\xa040.815/-73.045',
 'place': ''}
{'': '',
 '_id': ObjectId('6229044036c49561fbe12fd0'),
 'admin1': 'United States',
 'admin2': 'New York',
 'admin3': 'Suffolk',
 'code': 'Holtsville',
 'country': '00544',
 'place': '62'}
{'_id': ObjectId('6229044036c49561fbe12fd1'),
 'code': '\xa0\xa0\xa040.815/-73.045',
 'place': ''}
{'': '',
 '_id': ObjectId('6229044036c49561fbe12fd2'),
 'admin1': 'United States',
 'admin2': 'Massachusetts',
 'admin3': 'Worcester',
 'code': 'Gilbertville',
 'country': '01031',
 'place': '63'}
{'_id': ObjectId('6229044036c49561fbe12fd3'),
 'code': '\xa0\xa0\xa042.332/-72.199',
 'place': ''}
{'': '',
 '_id': ObjectId('6229044036c49561fbe12fd4'),
 'admin1': 'United States',
 'admin2': 'Massachusetts',
 'admin3': 'Hampshire',
 'code': 'Goshen',
 'country': '01032',
 'place': '64'}
{'_id': ObjectId('6229044036c49561fbe12fd5'),
 'code': '\xa0\xa0\xa042.44/-72.8',
 'place': ''}
{'': '',
 '_id': ObjectId('6229044036c49561fbe12fd6'),
 'admin1': 'United States',
 'admin2': 'Massachusetts',
 'admin3': 'Hampshire',
 'code': 'Haydenville',
 'country': '01039',
 'place': '65'}
{'_id': ObjectId('6229044036c49561fbe12fd7'),
 'code': '\xa0\xa0\xa042.382/-72.703',
 'place': ''}
{'': '',
 '_id': ObjectId('6229044036c49561fbe12fd8'),
 'admin1': 'United States',
 'admin2': 'Massachusetts',
 'admin3': 'Hampshire',
 'code': 'Florence',
 'country': '01062',
 'place': '66'}
{'_id': ObjectId('6229044036c49561fbe12fd9'),
 'code': '\xa0\xa0\xa042.322/-72.693',
 'place': ''}
{'': '',
 '_id': ObjectId('6229044036c49561fbe12fda'),
 'admin1': 'United States',
 'admin2': 'Massachusetts',
 'admin3': 'Hampshire',
 'code': 'North Hatfield',
 'country': '01066',
 'place': '67'}
{'_id': ObjectId('6229044036c49561fbe12fdb'),
 'code': '\xa0\xa0\xa042.411/-72.622',
 'place': ''}
{'': '',
 '_id': ObjectId('6229044036c49561fbe12fdc'),
 'admin1': 'United States',
 'admin2': 'Massachusetts',
 'admin3': 'Hampshire',
 'code': 'Plainfield',
 'country': '01070',
 'place': '68'}
{'_id': ObjectId('6229044036c49561fbe12fdd'),
 'code': '\xa0\xa0\xa042.514/-72.918',
 'place': ''}
{'': '',
 '_id': ObjectId('6229044036c49561fbe12fde'),
 'admin1': 'United States',
 'admin2': 'Massachusetts',
 'admin3': 'Hampshire',
 'code': 'Southampton',
 'country': '01073',
 'place': '69'}
{'_id': ObjectId('6229044036c49561fbe12fdf'),
 'code': '\xa0\xa0\xa042.225/-72.719',
 'place': ''}
{'': '',
 '_id': ObjectId('6229044036c49561fbe12fe0'),
 'admin1': 'United States',
 'admin2': 'Massachusetts',
 'admin3': 'Hampden',
 'code': 'Thorndike',
 'country': '01079',
 'place': '70'}
{'_id': ObjectId('6229044036c49561fbe12fe1'),
 'code': '\xa0\xa0\xa042.193/-72.33',
 'place': ''}
{'': '',

In [44]:
col=EltData["geonames"]
for x in col.find({"admin1":"United States"}):
    print(x)

{'_id': ObjectId('6229044036c49561fbe12f56'), 'place': '1', 'code': 'Four States', 'country': '26572', 'admin1': 'United States', 'admin2': 'West Virginia', 'admin3': 'Marion', '': ''}
{'_id': ObjectId('6229044036c49561fbe12f58'), 'place': '2', 'code': 'Myersville', 'country': '21773', 'admin1': 'United States', 'admin2': 'Maryland', 'admin3': 'Frederick', '': ''}
{'_id': ObjectId('6229044036c49561fbe12f5a'), 'place': '3', 'code': 'Fairfax', 'country': '22033', 'admin1': 'United States', 'admin2': 'Virginia', 'admin3': 'Fairfax', '': ''}
{'_id': ObjectId('6229044036c49561fbe12f5c'), 'place': '4', 'code': 'Alexandria', 'country': '22303', 'admin1': 'United States', 'admin2': 'Virginia', 'admin3': 'Fairfax', '': ''}
{'_id': ObjectId('6229044036c49561fbe12f5e'), 'place': '5', 'code': 'Alexandria', 'country': '22306', 'admin1': 'United States', 'admin2': 'Virginia', 'admin3': 'Fairfax', '': ''}
{'_id': ObjectId('6229044036c49561fbe12f60'), 'place': '6', 'code': 'Alexandria', 'country': '22310', 'admin1': 'United States', 'admin2': 'Virginia', 'admin3': 'Fairfax', '': ''}
{'_id': ObjectId('6229044036c49561fbe12f62'), 'place': '7', 'code': 'Alexandria', 'country': '22312', 'admin1': 'United States', 'admin2': 'Virginia', 'admin3': 'Fairfax', '': ''}
{'_id': ObjectId('6229044036c49561fbe12f64'), 'place': '8', 'code': 'Williamsburg', 'country': '23185', 'admin1': 'United States', 'admin2': 'Virginia', 'admin3': 'James City', '': ''}
{'_id': ObjectId('6229044036c49561fbe12f66'), 'place': '9', 'code': 'Richmond', 'country': '23230', 'admin1': 'United States', 'admin2': 'Virginia', 'admin3': 'Henrico', '': ''}
{'_id': ObjectId('6229044036c49561fbe12f68'), 'place': '10', 'code': 'Henrico', 'country': '23233', 'admin1': 'United States', 'admin2': 'Virginia', 'admin3': 'Henrico', '': ''}
{'_id': ObjectId('6229044036c49561fbe12f6a'), 'place': '11', 'code': 'Scottdale', 'country': '30079', 'admin1': 'United States', 'admin2': 'Georgia', 'admin3': 'DeKalb', '': ''}
{'_id': ObjectId('6229044036c49561fbe12f6c'), 'place': '12', 'code': 'Conley', 'country': '30288', 'admin1': 'United States', 'admin2': 'Georgia', 'admin3': 'Clayton', '': ''}
{'_id': ObjectId('6229044036c49561fbe12f6e'), 'place': '13', 'code': 'Ellenwood', 'country': '30294', 'admin1': 'United States', 'admin2': 'Georgia', 'admin3': 'Clayton', '': ''}
{'_id': ObjectId('6229044036c49561fbe12f70'), 'place': '14', 'code': 'Atlanta', 'country': '30319', 'admin1': 'United States', 'admin2': 'Georgia', 'admin3': 'DeKalb', '': ''}
{'_id': ObjectId('6229044036c49561fbe12f72'), 'place': '15', 'code': 'Atlanta', 'country': '30329', 'admin1': 'United States', 'admin2': 'Georgia', 'admin3': 'DeKalb', '': ''}
{'_id': ObjectId('6229044036c49561fbe12f74'), 'place': '16', 'code': 'Atlanta', 'country': '30341', 'admin1': 'United States', 'admin2': 'Georgia', 'admin3': 'DeKalb', '': ''}
{'_id': ObjectId('6229044036c49561fbe12f76'), 'place': '17', 'code': 'Atlanta', 'country': '30345', 'admin1': 'United States', 'admin2': 'Georgia', 'admin3': 'DeKalb', '': ''}
{'_id': ObjectId('6229044036c49561fbe12f78'), 'place': '18', 'code': 'Atlanta', 'country': '30346', 'admin1': 'United States', 'admin2': 'Georgia', 'admin3': 'DeKalb', '': ''}
{'_id': ObjectId('6229044036c49561fbe12f7a'), 'place': '19', 'code': 'Yulee', 'country': '32041', 'admin1': 'United States', 'admin2': 'Florida', 'admin3': 'Nassau', '': ''}
{'_id': ObjectId('6229044036c49561fbe12f7c'), 'place': '20', 'code': 'Edgewater', 'country': '32132', 'admin1': 'United States', 'admin2': 'Florida', 'admin3': 'Volusia', '': ''}
{'_id': ObjectId('6229044036c49561fbe12f7e'), 'place': '21', 'code': 'Cypress', 'country': '32432', 'admin1': 'United States', 'admin2': 'Florida', 'admin3': 'Jackson', '': ''}
{'_id': ObjectId('6229044036c49561fbe12f80'), 'place': '22', 'code': 'Alachua', 'country': '32615', 'admin1': 'United States', 'admin2': 'Florida', 'admin3': 'Alachua', '': ''}
{'_id': ObjectId('6229044036c49561fbe12f82'), 'place': '23', 'code': 'Chiefland', 'country': '32626', 'admin1': 'United States', 'admin2': 'Florida', 'admin3': 'Levy', '': ''}
{'_id': ObjectId('6229044036c49561fbe12f84'), 'place': '24', 'code': 'Melrose', 'country': '32666', 'admin1': 'United States', 'admin2': 'Florida', 'admin3': 'Putnam', '': ''}
{'_id': ObjectId('6229044036c49561fbe12f86'), 'place': '25', 'code': 'Mims', 'country': '32754', 'admin1': 'United States', 'admin2': 'Florida', 'admin3': 'Brevard', '': ''}
{'_id': ObjectId('6229044036c49561fbe12f88'), 'place': '26', 'code': 'Sanford', 'country': '32771', 'admin1': 'United States', 'admin2': 'Florida', 'admin3': 'Seminole', '': ''}
{'_id': ObjectId('6229044036c49561fbe12f8a'), 'place': '27', 'code': 'Lutz', 'country': '33548', 'admin1': 'United States', 'admin2': 'Florida', 'admin3': 'Hillsborough', '': ''}
{'_id': ObjectId('6229044036c49561fbe12f8c'), 'place': '28', 'code': 'Lutz', 'country': '33549', 'admin1': 'United States', 'admin2': 'Florida', 'admin3': 'Hillsborough', '': ''}
{'_id': ObjectId('6229044036c49561fbe12f8e'), 'place': '29', 'code': 'Odessa', 'country': '33556', 'admin1': 'United States', 'admin2': 'Florida', 'admin3': 'Hillsborough', '': ''}
{'_id': ObjectId('6229044036c49561fbe12f90'), 'place': '30', 'code': 'Seffner', 'country': '33583', 'admin1': 'United States', 'admin2': 'Florida', 'admin3': 'Hillsborough', '': ''}
{'_id': ObjectId('6229044036c49561fbe12f92'), 'place': '31', 'code': 'Valrico', 'country': '33594', 'admin1': 'United States', 'admin2': 'Florida', 'admin3': 'Hillsborough', '': ''}
{'_id': ObjectId('6229044036c49561fbe12f94'), 'place': '32', 'code': 'Wimauma', 'country': '33598', 'admin1': 'United States', 'admin2': 'Florida', 'admin3': 'Hillsborough', '': ''}
{'_id': ObjectId('6229044036c49561fbe12f96'), 'place': '33', 'code': 'Captiva', 'country': '33924', 'admin1': 'United States', 'admin2': 'Florida', 'admin3': 'Lee', '': ''}
{'_id': ObjectId('6229044036c49561fbe12f98'), 'place': '34', 'code': 'Placida', 'country': '33946', 'admin1': 'United States', 'admin2': 'Florida', 'admin3': 'Charlotte', '': ''}
{'_id': ObjectId('6229044036c49561fbe12f9a'), 'place': '35', 'code': 'Laurel', 'country': '34272', 'admin1': 'United States', 'admin2': 'Florida', 'admin3': 'Sarasota', '': ''}
{'_id': ObjectId('6229044036c49561fbe12f9c'), 'place': '36', 'code': 'Nokomis', 'country': '34274', 'admin1': 'United States', 'admin2': 'Florida', 'admin3': 'Sarasota', '': ''}
{'_id': ObjectId('6229044036c49561fbe12f9e'), 'place': '37', 'code': 'Dunnellon', 'country': '34430', 'admin1': 'United States', 'admin2': 'Florida', 'admin3': 'Marion', '': ''}
{'_id': ObjectId('6229044036c49561fbe12fa0'), 'place': '38', 'code': 'Dunnellon', 'country': '34431', 'admin1': 'United States', 'admin2': 'Florida', 'admin3': 'Marion', '': ''}
{'_id': ObjectId('6229044036c49561fbe12fa2'), 'place': '39', 'code': 'Dunnellon', 'country': '34432', 'admin1': 'United States', 'admin2': 'Florida', 'admin3': 'Marion', '': ''}
{'_id': ObjectId('6229044036c49561fbe12fa4'), 'place': '40', 'code': 'Dunnellon', 'country': '34433', 'admin1': 'United States', 'admin2': 'Florida', 'admin3': 'Citrus', '': ''}
{'_id': ObjectId('6229044036c49561fbe12fa6'), 'place': '41', 'code': 'Hernando', 'country': '34442', 'admin1': 'United States', 'admin2': 'Florida', 'admin3': 'Citrus', '': ''}
{'_id': ObjectId('6229044036c49561fbe12fa8'), 'place': '42', 'code': 'Homosassa', 'country': '34446', 'admin1': 'United States', 'admin2': 'Florida', 'admin3': 'Citrus', '': ''}
{'_id': ObjectId('6229044036c49561fbe12faa'), 'place': '43', 'code': 'Homosassa', 'country': '34448', 'admin1': 'United States', 'admin2': 'Florida', 'admin3': 'Citrus', '': ''}
{'_id': ObjectId('6229044036c49561fbe12fac'), 'place': '44', 'code': 'Lecanto', 'country': '34460', 'admin1': 'United States', 'admin2': 'Florida', 'admin3': 'Citrus', '': ''}
{'_id': ObjectId('6229044036c49561fbe12fae'), 'place': '45', 'code': 'Homosassa', 'country': '34487', 'admin1': 'United States', 'admin2': 'Florida', 'admin3': 'Citrus', '': ''}
{'_id': ObjectId('6229044036c49561fbe12fb0'), 'place': '46', 'code': 'Summerfield', 'country': '34491', 'admin1': 'United States', 'admin2': 'Florida', 'admin3': 'Marion', '': ''}
{'_id': ObjectId('6229044036c49561fbe12fb2'), 'place': '47', 'code': 'Hudson', 'country': '34667', 'admin1': 'United States', 'admin2': 'Florida', 'admin3': 'Pasco', '': ''}
{'_id': ObjectId('6229044036c49561fbe12fb4'), 'place': '48', 'code': 'Holiday', 'country': '34690', 'admin1': 'United States', 'admin2': 'Florida', 'admin3': 'Pasco', '': ''}
{'_id': ObjectId('6229044036c49561fbe12fb6'), 'place': '49', 'code': 'Hebron', 'country': '43025', 'admin1': 'United States', 'admin2': 'Ohio', 'admin3': 'Licking', '': ''}
{'_id': ObjectId('6229044036c49561fbe12fb8'), 'place': '50', 'code': 'Lebanon', 'country': '46052', 'admin1': 'United States', 'admin2': 'Indiana', 'admin3': 'Boone', '': ''}
{'_id': ObjectId('6229044036c49561fbe12fba'), 'place': '51', 'code': 'Belleville', 'country': '48111', 'admin1': 'United States', 'admin2': 'Michigan', 'admin3': 'Wayne', '': ''}
{'_id': ObjectId('6229044036c49561fbe12fbc'), 'place': '52', 'code': 'Germantown', 'country': '53022', 'admin1': 'United States', 'admin2': 'Wisconsin', 'admin3': 'Washington', '': ''}
{'_id': ObjectId('6229044036c49561fbe12fbe'), 'place': '53', 'code': 'Itasca', 'country': '60143', 'admin1': 'United States', 'admin2': 'Illinois', 'admin3': 'DuPage', '': ''}
{'_id': ObjectId('6229044036c49561fbe12fc0'), 'place': '54', 'code': 'Hinsdale', 'country': '60521', 'admin1': 'United States', 'admin2': 'Illinois', 'admin3': 'DuPage', '': ''}
{'_id': ObjectId('6229044036c49561fbe12fc2'), 'place': '55', 'code': 'Willowbrook', 'country': '60527', 'admin1': 'United States', 'admin2': 'Illinois', 'admin3': 'DuPage', '': ''}
{'_id': ObjectId('6229044036c49561fbe12fc4'), 'place': '56', 'code': 'Paris', 'country': '75462', 'admin1': 'United States', 'admin2': 'Texas', 'admin3': 'Lamar', '': ''}
{'_id': ObjectId('6229044036c49561fbe12fc6'), 'place': '57', 'code': 'Gardnerville', 'country': '89410', 'admin1': 'United States', 'admin2': 'Nevada', 'admin3': 'Douglas', '': ''}
{'_id': ObjectId('6229044036c49561fbe12fc8'), 'place': '58', 'code': 'Chatsworth', 'country': '91311', 'admin1': 'United States', 'admin2': 'California', 'admin3': 'Los Angeles', '': ''}
{'_id': ObjectId('6229044036c49561fbe12fca'), 'place': '59', 'code': 'Kihei', 'country': '96753', 'admin1': 'United States', 'admin2': 'Hawaii', 'admin3': 'Maui', '': ''}
{'_id': ObjectId('6229044036c49561fbe12fcc'), 'place': '60', 'code': 'Mount Vernon', 'country': '36560', 'admin1': 'United States', 'admin2': 'Alabama', 'admin3': 'Mobile', '': ''}
{'_id': ObjectId('6229044036c49561fbe12fce'), 'place': '61', 'code': 'Holtsville', 'country': '00501', 'admin1': 'United States', 'admin2': 'New York', 'admin3': 'Suffolk', '': ''}
{'_id': ObjectId('6229044036c49561fbe12fd0'), 'place': '62', 'code': 'Holtsville', 'country': '00544', 'admin1': 'United States', 'admin2': 'New York', 'admin3': 'Suffolk', '': ''}
{'_id': ObjectId('6229044036c49561fbe12fd2'), 'place': '63', 'code': 'Gilbertville', 'country': '01031', 'admin1': 'United States', 'admin2': 'Massachusetts', 'admin3': 'Worcester', '': ''}
{'_id': ObjectId('6229044036c49561fbe12fd4'), 'place': '64', 'code': 'Goshen', 'country': '01032', 'admin1': 'United States', 'admin2': 'Massachusetts', 'admin3': 'Hampshire', '': ''}
{'_id': ObjectId('6229044036c49561fbe12fd6'), 'place': '65', 'code': 'Haydenville', 'country': '01039', 'admin1': 'United States', 'admin2': 'Massachusetts', 'admin3': 'Hampshire', '': ''}
{'_id': ObjectId('6229044036c49561fbe12fd8'), 'place': '66', 'code': 'Florence', 'country': '01062', 'admin1': 'United States', 'admin2': 'Massachusetts', 'admin3': 'Hampshire', '': ''}
{'_id': ObjectId('6229044036c49561fbe12fda'), 'place': '67', 'code': 'North Hatfield', 'country': '01066', 'admin1': 'United States', 'admin2': 'Massachusetts', 'admin3': 'Hampshire', '': ''}
{'_id': ObjectId('6229044036c49561fbe12fdc'), 'place': '68', 'code': 'Plainfield', 'country': '01070', 'admin1': 'United States', 'admin2': 'Massachusetts', 'admin3': 'Hampshire', '': ''}
{'_id': ObjectId('6229044036c49561fbe12fde'), 'place': '69', 'code': 'Southampton', 'country': '01073', 'admin1': 'United States', 'admin2': 'Massachusetts', 'admin3': 'Hampshire', '': ''}
{'_id': ObjectId('6229044036c49561fbe12fe0'), 'place': '70', 'code': 'Thorndike', 'country': '01079', 'admin1': 'United States', 'admin2': 'Massachusetts', 'admin3': 'Hampden', '': ''}
{'_id': ObjectId('6229044036c49561fbe12fe2'), 'place': '71', 'code': 'Wales', 'country': '01081', 'admin1': 'United States', 'admin2': 'Massachusetts', 'admin3': 'Hampden', '': ''}
{'_id': ObjectId('6229044036c49561fbe12fe4'), 'place': '72', 'code': 'Wheelwright', 'country': '01094', 'admin1': 'United States', 'admin2': 'Massachusetts', 'admin3': 'Worcester', '': ''}
{'_id': ObjectId('6229044036c49561fbe12fe6'), 'place': '73', 'code': 'Worthington', 'country': '01098', 'admin1': 'United States', 'admin2': 'Massachusetts', 'admin3': 'Hampshire', '': ''}
{'_id': ObjectId('6229044036c49561fbe12fe8'), 'place': '74', 'code': 'Glendale', 'country': '01229', 'admin1': 'United States', 'admin2': 'Massachusetts', 'admin3': 'Berkshire', '': ''}
{'_id': ObjectId('6229044036c49561fbe12fea'), 'place': '75', 'code': 'Hinsdale', 'country': '01235', 'admin1': 'United States', 'admin2': 'Massachusetts', 'admin3': 'Berkshire', '': ''}
{'_id': ObjectId('6229044036c49561fbe12fec'), 'place': '76', 'code': 'Housatonic', 'country': '01236', 'admin1': 'United States', 'admin2': 'Massachusetts', 'admin3': 'Berkshire', '': ''}
{'_id': ObjectId('6229044036c49561fbe12fee'), 'place': '77', 'code': 'Middlefield', 'country': '01243', 'admin1': 'United States', 'admin2': 'Massachusetts', 'admin3': 'Hampshire', '': ''}
{'_id': ObjectId('6229044036c49561fbe12ff0'), 'place': '78', 'code': 'Otis', 'country': '01253', 'admin1': 'United States', 'admin2': 'Massachusetts', 'admin3': 'Berkshire', '': ''}
{'_id': ObjectId('6229044036c49561fbe12ff2'), 'place': '79', 'code': 'Sandisfield', 'country': '01255', 'admin1': 'United States', 'admin2': 'Massachusetts', 'admin3': 'Berkshire', '': ''}
{'_id': ObjectId('6229044036c49561fbe12ff4'), 'place': '80', 'code': 'Southfield', 'country': '01259', 'admin1': 'United States', 'admin2': 'Massachusetts', 'admin3': 'Berkshire', '': ''}
{'_id': ObjectId('6229044036c49561fbe12ff6'), 'place': '81', 'code': 'Greenfield', 'country': '01301', 'admin1': 'United States', 'admin2': 'Massachusetts', 'admin3': 'Franklin', '': ''}
{'_id': ObjectId('6229044036c49561fbe12ff8'), 'place': '82', 'code': 'Drury', 'country': '01343', 'admin1': 'United States', 'admin2': 'Massachusetts', 'admin3': 'Berkshire', '': ''}
{'_id': ObjectId('6229044036c49561fbe12ffa'), 'place': '83', 'code': 'Orange', 'country': '01364', 'admin1': 'United States', 'admin2': 'Massachusetts', 'admin3': 'Franklin', '': ''}
{'_id': ObjectId('6229044036c49561fbe12ffc'), 'place': '84', 'code': 'Fiskdale', 'country': '01518', 'admin1': 'United States', 'admin2': 'Massachusetts', 'admin3': 'Worcester', '': ''}
{'_id': ObjectId('6229044036c49561fbe12ffe'), 'place': '85', 'code': 'Whitinsville', 'country': '01588', 'admin1': 'United States', 'admin2': 'Massachusetts', 'admin3': 'Worcester', '': ''}
{'_id': ObjectId('6229044036c49561fbe13000'), 'place': '86', 'code': 'Boxborough', 'country': '01719', 'admin1': 'United States', 'admin2': 'Massachusetts', 'admin3': 'Middlesex', '': ''}
{'_id': ObjectId('6229044036c49561fbe13002'), 'place': '87', 'code': 'Fayville', 'country': '01745', 'admin1': 'United States', 'admin2': 'Massachusetts', 'admin3': 'Worcester', '': ''}
{'_id': ObjectId('6229044036c49561fbe13004'), 'place': '88', 'code': 'Hopedale', 'country': '01747', 'admin1': 'United States', 'admin2': 'Massachusetts', 'admin3': 'Worcester', '': ''}
{'_id': ObjectId('6229044036c49561fbe13006'), 'place': '89', 'code': 'Woodville', 'country': '01784', 'admin1': 'United States', 'admin2': 'Massachusetts', 'admin3': 'Middlesex', '': ''}
{'_id': ObjectId('6229044036c49561fbe13008'), 'place': '90', 'code': 'North Chelmsford', 'country': '01863', 'admin1': 'United States', 'admin2': 'Massachusetts', 'admin3': 'Middlesex', '': ''}
{'_id': ObjectId('6229044036c49561fbe1300a'), 'place': '91', 'code': 'Pinehurst', 'country': '01866', 'admin1': 'United States', 'admin2': 'Massachusetts', 'admin3': 'Middlesex', '': ''}
{'_id': ObjectId('6229044036c49561fbe1300c'), 'place': '92', 'code': 'Newbury', 'country': '01951', 'admin1': 'United States', 'admin2': 'Massachusetts', 'admin3': 'Essex', '': ''}
{'_id': ObjectId('6229044036c49561fbe1300e'), 'place': '93', 'code': 'Humarock', 'country': '02047', 'admin1': 'United States', 'admin2': 'Massachusetts', 'admin3': 'Plymouth', '': ''}
{'_id': ObjectId('6229044036c49561fbe13010'), 'place': '94', 'code': 'Sheldonville', 'country': '02070', 'admin1': 'United States', 'admin2': 'Massachusetts', 'admin3': 'Norfolk', '': ''}
{'_id': ObjectId('6229044036c49561fbe13012'), 'place': '95', 'code': 'Mattapan', 'country': '02126', 'admin1': 'United States', 'admin2': 'Massachusetts', 'admin3': 'Suffolk', '': ''}
{'_id': ObjectId('6229044036c49561fbe13014'), 'place': '96', 'code': 'Readville', 'country': '02137', 'admin1': 'United States', 'admin2': 'Massachusetts', 'admin3': 'Suffolk', '': ''}
{'_id': ObjectId('6229044036c49561fbe13016'), 'place': '97', 'code': 'Braintree', 'country': '02184', 'admin1': 'United States', 'admin2': 'Massachusetts', 'admin3': 'Norfolk', '': ''}
{'_id': ObjectId('6229044036c49561fbe13018'), 'place': '98', 'code': 'Braintree', 'country': '02185', 'admin1': 'United States', 'admin2': 'Massachusetts', 'admin3': 'Norfolk', '': ''}
{'_id': ObjectId('6229044036c49561fbe1301a'), 'place': '99', 'code': 'Avon', 'country': '02322', 'admin1': 'United States', 'admin2': 'Massachusetts', 'admin3': 'Norfolk', '': ''}
{'_id': ObjectId('6229044036c49561fbe1301c'), 'place': '100', 'code': 'Bryantville', 'country': '02327', 'admin1': 'United States', 'admin2': 'Massachusetts', 'admin3': 'Plymouth', '': ''}
{'_id': ObjectId('6229044036c49561fbe1301e'), 'place': '101', 'code': 'Monponsett', 'country': '02350', 'admin1': 'United States', 'admin2': 'Massachusetts', 'admin3': 'Plymouth', '': ''}
{'_id': ObjectId('6229044036c49561fbe13020'), 'place': '102', 'code': 'Newtonville', 'country': '02460', 'admin1': 'United States', 'admin2': 'Massachusetts', 'admin3': 'Middlesex', '': ''}
{'_id': ObjectId('6229044036c49561fbe13022'), 'place': '103', 'code': 'Onset', 'country': '02558', 'admin1': 'United States', 'admin2': 'Massachusetts', 'admin3': 'Plymouth', '': ''}
{'_id': ObjectId('6229044036c49561fbe13024'), 'place': '104', 'code': 'Cummaquid', 'country': '02637', 'admin1': 'United States', 'admin2': 'Massachusetts', 'admin3': 'Barnstable', '': ''}
{'_id': ObjectId('6229044036c49561fbe13026'), 'place': '105', 'code': 'Forestdale', 'country': '02644', 'admin1': 'United States', 'admin2': 'Massachusetts', 'admin3': 'Barnstable', '': ''}
{'_id': ObjectId('6229044036c49561fbe13028'), 'place': '106', 'code': 'Osterville', 'country': '02655', 'admin1': 'United States', 'admin2': 'Massachusetts', 'admin3': 'Barnstable', '': ''}
{'_id': ObjectId('6229044036c49561fbe1302a'), 'place': '107', 'code': 'South Yarmouth', 'country': '02664', 'admin1': 'United States', 'admin2': 'Massachusetts', 'admin3': 'Barnstable', '': ''}
{'_id': ObjectId('6229044036c49561fbe1302c'), 'place': '108', 'code': 'West Chatham', 'country': '02669', 'admin1': 'United States', 'admin2': 'Massachusetts', 'admin3': 'Barnstable', '': ''}
{'_id': ObjectId('6229044036c49561fbe1302e'), 'place': '109', 'code': 'Chartley', 'country': '02712', 'admin1': 'United States', 'admin2': 'Massachusetts', 'admin3': 'Bristol', '': ''}

In [164]:
df1=pd.read_json('geo_data.json')
df1

,place,code,country,admin1,admin2,admin3,
0,1,Four States,26572.0,United States,West Virginia,Marion,
1,,39.48/-80.31,NaN,NaN,NaN,NaN,NaN
2,2,Myersville,21773.0,United States,Maryland,Frederick,
3,,39.528/-77.551,NaN,NaN,NaN,NaN,NaN
4,3,Fairfax,22033.0,United States,Virginia,Fairfax,
...,...,...,...,...,...,...,...
797,,40.792/-74.245,NaN,NaN,NaN,NaN,NaN
798,199,Clark,7066.0,United States,New Jersey,Union,
799,,40.62/-74.311,NaN,NaN,NaN,NaN,NaN
800,200,Springfield,7081.0,United States,New Jersey,Union,
801,,40.701/-74.323,NaN,NaN,NaN,NaN,NaN

In [173]:
df1.rename(columns={'admin1':'Country'},inplace=True)
df1.columns

Index(['place', 'code', 'country', 'Country', 'admin2', 'admin3', ''], dtype='object')

In [174]:
df1.rename(columns={'admin2':'state'},inplace=True)
df1.columns

Index(['place', 'code', 'country', 'Country', 'state', 'admin3', ''], dtype='object')

In [175]:
df1.rename(columns={'admin3':'County'},inplace=True)
df1.columns

Index(['place', 'code', 'country', 'Country', 'state', 'County', ''], dtype='object')

In [176]:
df1.rename(columns={'country':'country_code'},inplace=True)
df1.columns

Index(['place', 'code', 'country_code', 'Country', 'state', 'County', ''], dtype='object')

In [177]:
df1.rename(columns={'code':'codename'},inplace=True)
df1.columns

Index(['place', 'codename', 'country_code', 'Country', 'state', 'County', ''], dtype='object')

In [191]:
df1.rename(columns={'Country':'country'},inplace=True)
df1.columns

Index(['place', 'codename', 'country_code', 'country', 'state', 'County'], dtype='object')

In [193]:
df1.rename(columns={'place':'place_id'},inplace=True)
df1.columns

Index(['place_id', 'codename', 'country_code', 'country', 'state', 'County'], dtype='object')

In [194]:
df1.head()

,place_id,codename,country_code,country,state,County
0,1,Four States,26572.0,United States,West Virginia,Marion
1,,39.48/-80.31,NaN,NaN,NaN,NaN
2,2,Myersville,21773.0,United States,Maryland,Frederick
3,,39.528/-77.551,NaN,NaN,NaN,NaN
4,3,Fairfax,22033.0,United States,Virginia,Fairfax

In [188]:
df1.loc[::6]

,place,codename,country_code,Country,state,County,
0,1,Four States,26572.0,United States,West Virginia,Marion,
6,4,Alexandria,22303.0,United States,Virginia,Fairfax,
12,7,Alexandria,22312.0,United States,Virginia,Fairfax,
18,10,Henrico,23233.0,United States,Virginia,Henrico,
24,13,Ellenwood,30294.0,United States,Georgia,Clayton,
...,...,...,...,...,...,...,...
774,187,Cobalt,6414.0,United States,Connecticut,Middlesex,
780,190,Marion,6444.0,United States,Connecticut,Hartford,
786,193,Lakeside,6758.0,United States,Connecticut,Litchfield,
792,196,Cranford,7016.0,United States,New Jersey,Union,
798,199,Clark,7066.0,United States,New Jersey,Union,

In [189]:
df1.drop(df1.columns[6], axis=1, inplace=True)

In [190]:
df1.head()

,place,codename,country_code,Country,state,County
0,1,Four States,26572.0,United States,West Virginia,Marion
1,,39.48/-80.31,NaN,NaN,NaN,NaN
2,2,Myersville,21773.0,United States,Maryland,Frederick
3,,39.528/-77.551,NaN,NaN,NaN,NaN
4,3,Fairfax,22033.0,United States,Virginia,Fairfax

In [49]:
df =  pd.read_json('geo_data.json')
df

,place,code,country,admin1,admin2,admin3,
0,1,Four States,26572.0,United States,West Virginia,Marion,
1,,39.48/-80.31,NaN,NaN,NaN,NaN,NaN
2,2,Myersville,21773.0,United States,Maryland,Frederick,
3,,39.528/-77.551,NaN,NaN,NaN,NaN,NaN
4,3,Fairfax,22033.0,United States,Virginia,Fairfax,
...,...,...,...,...,...,...,...
797,,40.792/-74.245,NaN,NaN,NaN,NaN,NaN
798,199,Clark,7066.0,United States,New Jersey,Union,
799,,40.62/-74.311,NaN,NaN,NaN,NaN,NaN
800,200,Springfield,7081.0,United States,New Jersey,Union,
801,,40.701/-74.323,NaN,NaN,NaN,NaN,NaN

In [50]:
df.head()

,place,code,country,admin1,admin2,admin3,
0,1,Four States,26572.0,United States,West Virginia,Marion,
1,,39.48/-80.31,NaN,NaN,NaN,NaN,NaN
2,2,Myersville,21773.0,United States,Maryland,Frederick,
3,,39.528/-77.551,NaN,NaN,NaN,NaN,NaN
4,3,Fairfax,22033.0,United States,Virginia,Fairfax,

In [51]:
df.tail(10)

    place               code  country         admin1      admin2 admin3
792   196           Cranford   7016.0  United States  New Jersey  Union
793           40.655/-74.306      NaN            NaN         NaN    NaN  NaN
794   197             Orange   7050.0  United States  New Jersey  Essex
795           40.769/-74.236      NaN            NaN         NaN    NaN  NaN
796   198             Orange   7051.0  United States  New Jersey  Essex
797           40.792/-74.245      NaN            NaN         NaN    NaN  NaN
798   199              Clark   7066.0  United States  New Jersey  Union
799            40.62/-74.311      NaN            NaN         NaN    NaN  NaN
800   200        Springfield   7081.0  United States  New Jersey  Union
801           40.701/-74.323      NaN            NaN         NaN    NaN  NaN

In [52]:
df.rename(columns={'place':'place_id'},inplace=True)
df.columns

Index(['place_id', 'code', 'country', 'admin1', 'admin2', 'admin3', ''], dtype='object')

In [53]:
df.head()

,place_id,code,country,admin1,admin2,admin3,
0,1,Four States,26572.0,United States,West Virginia,Marion,
1,,39.48/-80.31,NaN,NaN,NaN,NaN,NaN
2,2,Myersville,21773.0,United States,Maryland,Frederick,
3,,39.528/-77.551,NaN,NaN,NaN,NaN,NaN
4,3,Fairfax,22033.0,United States,Virginia,Fairfax,

In [121]:
for index, row in df.iterrows():
     if '/-' in row['code']:
       geocode =  print(row["code"])

   39.48/-80.31
   39.528/-77.551
   38.878/-77.388
   38.791/-77.081
   38.759/-77.087
   38.779/-77.119
   38.819/-77.148
   37.273/-76.732
   37.592/-77.495
   37.464/-77.398
   33.793/-84.259
   33.637/-84.337
   33.617/-84.294
   33.869/-84.335
   33.824/-84.321
   33.888/-84.29
   33.851/-84.287
   33.927/-84.333
   30.623/-81.59
   28.982/-80.91
   30.716/-85.078
   29.813/-82.472
   29.483/-82.881
   29.732/-82.028
   28.697/-80.866
   28.801/-81.285
   28.139/-82.482
   28.137/-82.461
   28.142/-82.591
   27.872/-82.439
   27.941/-82.242
   27.701/-82.315
   26.521/-82.18
   26.832/-82.265
   27.147/-82.426
   27.144/-82.464
   29.049/-82.461
   29.139/-82.533
   29.102/-82.341
   28.995/-82.52
   28.922/-82.39
   28.751/-82.514
   28.788/-82.568
   28.859/-82.509
   28.781/-82.615
   29.011/-82.032
   28.365/-82.676
   28.191/-82.728
   39.953/-82.492
   40.045/-86.464
   42.195/-83.485
   43.219/-88.117
   41.972/-88.02
   41.8/-87.929
   41.745/-87.933
   33.68/-95.491
   38.87/-119.611
   34.258/-118.591
   20.744/-156.448
   31.097/-88.035
   40.815/-73.045
   40.815/-73.045
   42.332/-72.199
   42.44/-72.8
   42.382/-72.703
   42.322/-72.693
   42.411/-72.622
   42.514/-72.918
   42.225/-72.719
   42.193/-72.33
   42.063/-72.205
   42.358/-72.141
   42.384/-72.931
   42.279/-73.344
   42.43/-73.072
   42.265/-73.375
   42.356/-73.01
   42.193/-73.092
   42.109/-73.116
   42.078/-73.261
   42.601/-72.624
   42.643/-72.986
   42.613/-72.292
   42.123/-72.118
   42.115/-71.664
   42.488/-71.518
   42.293/-71.503
   42.127/-71.538
   42.238/-71.562
   42.635/-71.391
   42.529/-71.228
   42.783/-70.847
   42.143/-70.694
   42.035/-71.387
   42.274/-71.094
   42.24/-71.137
   42.209/-70.996
   42.18/-71.089
   42.126/-71.044
   42.041/-70.827
   42.019/-70.847
   42.352/-71.208
   41.748/-70.658
   41.701/-70.277
   41.683/-70.514
   41.63/-70.384
   41.674/-70.195
   41.681/-69.991
   41.949/-71.226
   41.422/-70.931
   41.756/-71.067
   41.621/-71.089
   41.594/-71.252
   43.154/-70.658
   43.975/-70.792
   43.276/-70.598
   43.796/-70.414
   43.826/-70.924
   43.89/-70.195
   43.471/-70.806
   43.981/-69.938
   44.193/-70.716
   44.664/-70.797
   44.288/-70.368
   44.46/-70.3
   44.202/-70.375
   44.026/-70.114
   44.563/-70.536
   44.69/-71.011
   44.349/-70.071
   45.235/-69.57
   45.086/-68.923
   44.901/-68.626
   45.551/-67.744
   45.341/-69.042
   44.792/-68.578
   44.793/-69.132
   44.968/-69.108
   45.364/-68.291
   44.884/-68.984
   45.891/-67.847
   44.546/-68.731
   44.726/-68.788
   45.141/-69.322
   44.884/-69.107
   44.908/-68.686
   45.457/-68.357
   44.513/-67.606
   44.242/-68.358
   44.254/-68.557
   44.405/-67.985
   44.675/-67.25
   44.896/-67.224
   44.551/-67.604
   44.336/-68.638
   44.491/-68.179
   44.497/-67.95
   44.175/-68.675
   44.206/-68.705
   44.488/-68.506
   47.329/-68.333
   46.013/-68.465
   45.068/-69.886
   44.568/-69.14
   44.926/-69.232
   44.699/-69.103
   45.336/-70.628
   44.374/-69.331
   44.411/-69.147
   44.787/-69.402
   44.488/-68.931
   44.822/-70.222
   44.695/-70.243
   44.601/-69.333
   43.996/-72.411
   44.508/-73.05
   44.692/-73.024
   43.663/-72.796
   44.95/-72.138
   41.748/-72.887
   41.837/-72.825
   41.733/-72.377
   41.854/-71.868
   42.022/-71.939
   41.696/-72.087
   41.366/-73.257
   41.567/-72.558
   41.428/-73.355
   41.342/-72.44
   41.564/-72.926
   41.566/-72.892
   41.534/-72.7
   41.675/-73.242
   41.038/-73.581
   40.583/-74.279
   40.655/-74.306
   40.769/-74.236
   40.792/-74.245
   40.62/-74.311
   40.701/-74.323

TypeError: argument of type 'float' is not iterable

In [135]:
#filtering and moving into a new df

index = [I for I in range(1,800,2)]
df_code  = df.filter(items = index, axis=0)

In [136]:
df_code = df.filter(items = index, axis=0)

In [137]:
df_code

,place_id,code,country,admin1,admin2,admin3,,f_code
1,,39.48/-80.31,NaN,NaN,NaN,NaN,NaN,39.48/-80.31
3,,39.528/-77.551,NaN,NaN,NaN,NaN,NaN,39.528/-77.551
5,,38.878/-77.388,NaN,NaN,NaN,NaN,NaN,38.878/-77.388
7,,38.791/-77.081,NaN,NaN,NaN,NaN,NaN,38.791/-77.081
9,,38.759/-77.087,NaN,NaN,NaN,NaN,NaN,38.759/-77.087
...,...,...,...,...,...,...,...,...
791,,40.583/-74.279,NaN,NaN,NaN,NaN,NaN,40.583/-74.279
793,,40.655/-74.306,NaN,NaN,NaN,NaN,NaN,40.655/-74.306
795,,40.769/-74.236,NaN,NaN,NaN,NaN,NaN,40.769/-74.236
797,,40.792/-74.245,NaN,NaN,NaN,NaN,NaN,40.792/-74.245
799,,40.62/-74.311,NaN,NaN,NaN,NaN,NaN,40.62/-74.311

In [138]:
df_code=df['code']

In [139]:
df_code

1           39.48/-80.31
3         39.528/-77.551
5         38.878/-77.388
7         38.791/-77.081
9         38.759/-77.087
             ...
791       40.583/-74.279
793       40.655/-74.306
795       40.769/-74.236
797       40.792/-74.245
799        40.62/-74.311
Name: code, Length: 400, dtype: object

In [111]:
df.dtypes

place_id     object
code         object
country     float64
admin1       object
admin2       object
admin3       object
             object
f_code       object
dtype: object

In [152]:
index = [I for I in range(0,800,2)]
df_code1  = df.filter(items = index, axis=0)

In [153]:
df_code1 = df.filter(items = index, axis=0)

In [155]:
df_code1.head()

Empty DataFrame
Columns: [place_id, code, country, admin1, admin2, admin3, , f_code]
Index: []

In [156]:
df.head()

,place_id,code,country,admin1,admin2,admin3,,f_code
1,,39.48/-80.31,NaN,NaN,NaN,NaN,NaN,39.48/-80.31
3,,39.528/-77.551,NaN,NaN,NaN,NaN,NaN,39.528/-77.551
5,,38.878/-77.388,NaN,NaN,NaN,NaN,NaN,38.878/-77.388
7,,38.791/-77.081,NaN,NaN,NaN,NaN,NaN,38.791/-77.081
9,,38.759/-77.087,NaN,NaN,NaN,NaN,NaN,38.759/-77.087

In [157]:
df.drop('f_code', axis=1, inplace=True)

In [159]:
df.drop('country',axis=1, inplace=True)

In [161]:
df.drop(['admin1','admin2','admin3'],axis=1, inplace=True)

In [163]:
df.tail(10)

    place_id               code
781              41.564/-72.926  NaN
783              41.566/-72.892  NaN
785                41.534/-72.7  NaN
787              41.675/-73.242  NaN
789              41.038/-73.581  NaN
791              40.583/-74.279  NaN
793              40.655/-74.306  NaN
795              40.769/-74.236  NaN
797              40.792/-74.245  NaN
799               40.62/-74.311  NaN

In [120]:
df["f_code"]

0            Four States
1           39.48/-80.31
2             Myersville
3         39.528/-77.551
4                Fairfax
             ...
797       40.792/-74.245
798                Clark
799        40.62/-74.311
800          Springfield
801       40.701/-74.323
Name: f_code, Length: 802, dtype: object

In [107]:
df["f_code"]

0            Four States
1           39.48/-80.31
2             Myersville
3         39.528/-77.551
4                Fairfax
             ...
797       40.792/-74.245
798                Clark
799        40.62/-74.311
800          Springfield
801       40.701/-74.323
Name: f_code, Length: 802, dtype: object

In [97]:
df.iloc[1:2,1:2]

              code
1     39.48/-80.31

In [98]:
df.iloc[:,1:2]

                  code
0          Four States
1         39.48/-80.31
2           Myersville
3       39.528/-77.551
4              Fairfax
..                 ...
797     40.792/-74.245
798              Clark
799      40.62/-74.311
800        Springfield
801     40.701/-74.323

[802 rows x 1 columns]

In [99]:
#li = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]
for i in range(len('code')):
    if 3 <= i: #along with other condition
        continue
    print(i)

0
1
2

In [108]:
df.head()

,place_id,code,country,admin1,admin2,admin3,,f_code
0,1,Four States,26572.0,United States,West Virginia,Marion,,Four States
1,,39.48/-80.31,NaN,NaN,NaN,NaN,NaN,39.48/-80.31
2,2,Myersville,21773.0,United States,Maryland,Frederick,,Myersville
3,,39.528/-77.551,NaN,NaN,NaN,NaN,NaN,39.528/-77.551
4,3,Fairfax,22033.0,United States,Virginia,Fairfax,,Fairfax